import mysql.connector
con = mysql.connector.connect(host='localhost',user='root',passwd='root')
mycur=con.cursor()
mycur.execute('use school')
mycur.execute('select * from student')
print('Given records are:')
for x in mycur:
    print(x)
print('Total ',mycur.rowcount,'records are present')
mycur.execute('select * from student')
data=mycur.fetchone()
print('Record by fetchone() command:')
print(data)
data=mycur.fetchmany(3)
print('Records by fetchmany(3) command:')
print(data)
data=mycur.fetchmany(3)
print('Using fetchmany(3) command:')
print(data)
mycur.execute('select * from student')
print('Using fetchall() command:')
for i in mycur.fetchall():
    print(i)
con.close()
